# http://travis-ci.org/#!/ipython/ipyparallel
language: python
python:
    - "nightly"
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install:
    - pip install --upgrade setuptools pip
    - pip install --pre --upgrade .[test] distributed joblib codecov
script:
    - pytest --maxfail=3 --cov ipyparallel -vsx ipyparallel/tests
after_success:
    - codecov
matrix:
    allow_failures:
        - python: "nightly"
