# http://travis-ci.org/#!/ipython/ipyparallel
language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install https://github.com/joblib/joblib/archive/master.zip # while joblib 0.10 isn't out
    - pip install --pre --upgrade -f travis-wheels/wheelhouse .[test] distributed coveralls
script:
    - iptest --coverage xml ipyparallel.tests -- -vsx
after_success:
    - coveralls
