# http://travis-ci.org/#!/ipython/ipyparallel
language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install:
    - pip install --upgrade setuptools pip
    - pip install --pre --upgrade .[test] distributed joblib codecov
script:
    - iptest --coverage xml ipyparallel.tests -- -vsx
after_success:
    - codecov
